version: "3"

services:
  mysql-master:
    container_name: db-mysql-master
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - master-data:/var/lib/mysql
      - ./master-config:/etc/mysql/conf.d  # 마스터 설정 파일 마운트
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=1'  # 마스터의 고유 server-id
      - '--log-bin=mysql-bin'
      - '--binlog-do-db=${MYSQL_DATABASE}'  # 복제할 DB 지정
    ports:
      - '3307:3306'
    expose:
      - "3306"
    networks:
      - app-tier

  mysql-slave1:
    container_name: db-mysql-slave1
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - slave1-data:/var/lib/mysql
      - ./slave-config:/etc/mysql/conf.d  # 슬레이브 설정 파일 마운트
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=2'  # 슬레이브의 고유 server-id
      - '--relay-log=relay-log-bin'
    ports:
      - '3308:3306'
    expose:
      - "3306"
    depends_on:
      - mysql-master
    networks:
      - app-tier

  mysql-slave2:
    container_name: db-mysql-slave2
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - slave2-data:/var/lib/mysql
      - ./slave-config:/etc/mysql/conf.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=3'
      - '--relay-log=relay-log-bin'
    ports:
      - '3309:3306'
    expose:
      - "3306"
    depends_on:
      - mysql-master
    networks:
      - app-tier

  mysql-slave3:
    container_name: db-mysql-slave3
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - slave3-data:/var/lib/mysql
      - ./slave-config:/etc/mysql/conf.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=4'
      - '--relay-log=relay-log-bin'
    ports:
      - '3310:3306'
    expose:
      - "3306"
    depends_on:
      - mysql-master
    networks:
      - app-tier

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-tier
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "1111"

networks:
  app-tier:
    driver: bridge

volumes:
  master-data:
  slave1-data:  # 첫 번째 슬레이브에 대한 볼륨
  slave2-data:  # 두 번째 슬레이브에 대한 볼륨
  slave3-data:  # 세 번째 슬레이브에 대한 볼륨
  redis-data: