spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery?&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # 생성된 SQL 출력
        format_sql: true
        use_sql_comments: true
    show-sql: true

jwt:
  secret: f46399d13753c46d03c1d90971b3d1072f470434a2f8266b0b1021281e46f69a

springdoc:
  version: v1.0.0
  packages-to-scan: com.example.delivery
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
